# Generated by Django 5.1.1 on 2024-09-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('goodsName', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('goodsDesc', models.TextField(blank=True, null=True)),
                ('goodsImg', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('discountPrice', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('situation_id', models.AutoField(primary_key=True, serialize=False)),
                ('situationCategory', models.CharField(max_length=50)),
                ('situation', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Situation',
                'verbose_name_plural': 'Situations',
                'db_table': 'situation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=150)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.situation')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('itemCnt', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
